title: Klck
description: A sample-accurate metronome for iPhone, iPad, and Mac.
theme: jekyll-theme-minimal
show_downloads: false

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /klck/icon.png
